# Generated by Django 4.2.4 on 2023-08-12 22:45

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.upload_user_image, verbose_name='آواتار'),
        ),
    ]
