# Generated by Django 4.2.4 on 2023-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد فعال سازی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت(فعال/غیرفعال)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='مدیر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='مدیرکل'),
        ),
    ]
