# Generated by Django 4.2.4 on 2023-08-23 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('description', models.TextField(max_length=650, verbose_name='شرح دوره')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت دوره')),
                ('tags', models.CharField(max_length=500, verbose_name='کلمات کلیدی')),
                ('courseImageName', models.ImageField(upload_to='', verbose_name='تصویر دوره')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('updateDate', models.DateField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('demoFileName', models.FileField(upload_to='', verbose_name='ویدیو دمو دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'db_table': 't_courses',
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelTitle', models.CharField(max_length=150, verbose_name='عنوان سطح دوره')),
            ],
            options={
                'verbose_name': 'سطح دوره',
                'verbose_name_plural': 'سطح دوره',
                'db_table': 't_course_level',
            },
        ),
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusTitle', models.CharField(max_length=150, verbose_name='عنوان وضعیت دوره')),
            ],
            options={
                'verbose_name': 'وضعیت دوره',
                'verbose_name_plural': 'وضعیت دوره',
                'db_table': 't_course_status',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeTitle', models.CharField(max_length=150, verbose_name='عنوان قسمت')),
                ('episodeTime', models.TimeField(verbose_name='زمان')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان بودن')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='course.course', verbose_name='دوره مربوطه')),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت ها',
                'db_table': 't_episodes',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupTitle', models.CharField(max_length=200, verbose_name='عنوان گروه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubGroups', to='course.coursegroup', verbose_name='زیر گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
                'db_table': 't_course_groups',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='courseLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_level', to='course.courselevel', verbose_name='سطح دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_status', to='course.coursestatus', verbose_name='وضعیت دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_group', to='course.coursegroup', verbose_name='گروه اصلی'),
        ),
        migrations.AddField(
            model_name='course',
            name='subGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_subgroup', to='course.coursegroup', verbose_name='گروه اصلی'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_user', to=settings.AUTH_USER_MODEL, verbose_name='مدرس'),
        ),
    ]
