# Generated by Django 4.2.4 on 2023-08-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت (فعال/غیرفعال)'),
        ),
    ]
