# Generated by Django 4.2.4 on 2023-08-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursegroup_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'verbose_name': 'گروه دوره ها', 'verbose_name_plural': 'گروه های دوره ها'},
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت (فعال/غیرفعال)'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubGroups', to='course.coursegroup', verbose_name=' گروه والد'),
        ),
    ]
