# Generated by Django 4.2.4 on 2023-08-26 10:24

import apps.course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_coursegroup_options_course_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseImageName',
            field=models.ImageField(upload_to=apps.course.models.upload_course_image, verbose_name='تصویر دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='demoFileName',
            field=models.FileField(upload_to=apps.course.models.upload_course_demo, verbose_name='ویدیو دمو دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_subgroup', to='course.coursegroup', verbose_name='گروه فرعی'),
        ),
    ]
