# Generated by Django 4.2.4 on 2023-09-09 11:18

import apps.course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_courseimagename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episodefilename',
            field=models.FileField(default='/images/k.png', upload_to=apps.course.models.upload_episode_file, verbose_name='فایل قسمت'),
            preserve_default=False,
        ),
    ]
