# Generated by Django 4.2.4 on 2023-09-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_episode_episodefilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episodeTime',
            field=models.DurationField(verbose_name='زمان'),
        ),
    ]
