# Generated by Django 4.2.4 on 2023-09-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_episode_episodetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
