# Generated by Django 4.2.4 on 2023-09-13 13:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_createdate_alter_course_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='شرح دوره'),
        ),
    ]
