# Generated by Django 4.2.4 on 2023-09-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_remove_usercourse_course_remove_usercourse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_teacher', to=settings.AUTH_USER_MODEL, verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(related_name='courses_of_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که دوره رو تهیه کردن'),
        ),
    ]
