# Generated by Django 4.2.4 on 2023-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_coursecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='comment',
            field=models.TextField(max_length=700, verbose_name='متن نظر'),
        ),
    ]
