# Generated by Django 4.2.4 on 2023-09-23 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0013_alter_coursecomment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False, verbose_name='وضعیت پسندیدن')),
                ('vote_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='course.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده لایک')),
            ],
            options={
                'verbose_name': 'پسند',
                'verbose_name_plural': 'پسند ها',
                'db_table': 't_votes',
            },
        ),
    ]
