# Generated by Django 4.2.4 on 2023-08-19 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletType',
            fields=[
                ('type_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_title', models.CharField(max_length=150, verbose_name='عنوان نوع تراکنش')),
            ],
            options={
                'verbose_name': 'نوع تراکنش',
                'verbose_name_plural': 'نوع تراکنش ها',
                'db_table': 't_wallet_type',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('description', models.CharField(max_length=500, verbose_name='شرح')),
                ('is_pay', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ و ساعت"')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets_of_wallet_type', to='userpanel.wallettype', verbose_name='نوع تراکنش')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets_of_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول ها',
                'db_table': 't_wallets',
            },
        ),
    ]
