# Generated by Django 4.2.4 on 2023-08-19 18:04

from django.contrib.auth.management import create_permissions
from django.db import migrations


def rename_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    db_alias = schema_editor.connection.alias
    create_permissions(apps, verbosity=0, interactive=False, db_alias=db_alias)
    permission = Permission.objects.get(codename='change_wallet')
    permission.name = 'میتونه کیف پول را تغییر دهد'
    permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_alter_wallet_options'),
    ]

    operations = [
        migrations.RunPython(rename_permission),
    ]
