# Generated by Django 4.2.4 on 2023-08-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0005_auto_20230823_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول ها'},
        ),
    ]
