# Generated by Django 4.2.4 on 2023-09-13 22:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0008_alter_course_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=150, verbose_name='کد تخفیف')),
                ('discount_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('usable_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد استفاده')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='شروع استفاده')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='پایان استفاده')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
                'db_table': 't_discounts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sum', models.IntegerField(verbose_name='جمع فاکتور')),
                ('is_finaly', models.BooleanField(default=False, verbose_name='وضعیت نهایی شده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت فاکتور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
                'db_table': 't_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='course.course', verbose_name='دوره')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order.order', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ریزفاکتور',
                'verbose_name_plural': 'ریزفاکتور ها',
                'db_table': 't_order_details',
            },
        ),
    ]
